User.create ([
			{ email: 'dande313@aol.com', password: 'abc123', admin: true},
			{ email: 'test@aol.com', password: 'abc123', admin: false}
	])

Project.create ([
	{ title: "Tower of Hanoi", info: "Completed AI, need to transfer from CLI to Heroku", repo_url: "https://github.com/dande313/Hanoi_v3", assistance_needed: false},
	{ title: "Science Journal", info: "Article show pages navigate using JQuery, but have difficulty when an article is deleted.", repo_url: "https://github.com/dande313/university-science-journal-V2", assistance_needed: true},
	{ title: "Top BoardGames Ruby CLI", info: "Working on adding prices for board games (located in dynamic JSON)", repo_url: "https://github.com/dande313/top_boardgames_ruby_cli", assistance_needed: false},
	{ title: "Art Collection", info: "Moving from Sinatra to Rails", repo_url: "https://github.com/dande313/Art-Collection", assistance_needed: true},
	{ title: "Team Collaborator", info: "Working in tidying up project with some sweet CSS", repo_url: "https://github.com/dande313/team_collab", assistance_needed: false},
	{ title: "Trivia Game", info: "Trouble getting answer box to automatically submit when timer runs out", repo_url: "https://github.com/dande313/React_Trivia_Game", assistance_needed: true},
	{ title: "Trivia Game", info: "Attempting to select 10 random trivia questions, when user hits PLAY", repo_url: "https://github.com/dande313/React_Trivia_Game", assistance_needed: true},
	{ title: "Tower of Hanoi", info: "Reworking instructions", repo_url: "https://github.com/dande313/Hanoi_v3", assistance_needed: false},
	{ title: "Art Collection", info: "Moving from Sinatra to Rails", repo_url: "https://github.com/dande313/Art-Collection", assistance_needed: true},
	{ title: "Science Journal", info: "Adding links for creating topics.", repo_url: "https://github.com/dande313/university-science-journal-V2", assistance_needed: false},
	{ title: "Science Journal", info: "Need to transfer from SQLite3 gem to PG gem, required for Heroku deployment.", repo_url: "https://github.com/dande313/university-science-journal-V2", assistance_needed: true},
	{ title: "Top BoardGames Ruby CLI", info: "Fixed Redirect issue on create new", repo_url: "https://github.com/dande313/top_boardgames_ruby_cli", assistance_needed: false},
	{ title: "Team Collaborator", info: "Wondering if we can get JSON to naturally ramify in application...", repo_url: "https://github.com/dande313/team_collab", assistance_needed: true},
	{ title: "Tower of Hanoi", info: "Having difficulty getting disks to render correctly when displaying more than 40. Want to get up to 64.", repo_url: "https://github.com/dande313/Hanoi_v3", assistance_needed: true},
	{ title: "Trivia Game", info: "PLAY link troubleshooting", repo_url: "https://github.com/dande313/React_Trivia_Game", assistance_needed: true},
	{ title: "Tower of Hanoi", info: "AI attempting to escape the box.", repo_url: "https://github.com/dande313/Hanoi_v3", assistance_needed: false},
	{ title: "Art Collection", info: "Adjusting to allow for display of image thumbnail", repo_url: "https://github.com/dande313/Art-Collection", assistance_needed: false},
	{ title: "Science Journal", info: "Adding option to add Department.", repo_url: "https://github.com/dande313/university-science-journal-V2", assistance_needed: true},
	{ title: "Top BoardGames Ruby CLI", info: "Working on Alert when game is on sale", repo_url: "https://github.com/dande313/top_boardgames_ruby_cli", assistance_needed: true},
	{ title: "Trivia Game", info: "Adding JQuery render of questions", repo_url: "https://github.com/dande313/React_Trivia_Game", assistance_needed: false},
	{ title: "Tower of Hanoi", info: "Porting to Minecraft server", repo_url: "https://github.com/dande313/Hanoi_v3", assistance_needed: true},
	{ title: "Art Collection", info: "Adding copyright complaint submission form", repo_url: "https://github.com/dande313/Art-Collection", assistance_needed: false},
	{ title: "Art Collection", info: "Moving from Sinatra to Rails", repo_url: "https://github.com/dande313/Art-Collection", assistance_needed: true},
	{ title: "Team Collaborator", info: "Working in tidying up project with some sweet CSS", repo_url: "https://github.com/dande313/team_collab", assistance_needed: false},
	{ title: "Trivia Game", info: "Trouble getting answer box to automatically submit when timer runs out", repo_url: "https://github.com/dande313/React_Trivia_Game", assistance_needed: true},
	{ title: "Trivia Game", info: "Attempting to select 10 random trivia questions, when user hits PLAY", repo_url: "https://github.com/dande313/React_Trivia_Game", assistance_needed: true},
	{ title: "Tower of Hanoi", info: "Reworking instructions", repo_url: "https://github.com/dande313/Hanoi_v3", assistance_needed: false},
	{ title: "Art Collection", info: "Moving from Sinatra to Rails", repo_url: "https://github.com/dande313/Art-Collection", assistance_needed: true},
	{ title: "Science Journal", info: "Adding links for creating topics.", repo_url: "https://github.com/dande313/university-science-journal-V2", assistance_needed: false},
	{ title: "Science Journal", info: "Need to transfer from SQLite3 gem to PG gem, required for Heroku deployment.", repo_url: "https://github.com/dande313/university-science-journal-V2", assistance_needed: true},
	{ title: "Top BoardGames Ruby CLI", info: "Fixed Redirect issue on create new", repo_url: "https://github.com/dande313/top_boardgames_ruby_cli", assistance_needed: false},
	{ title: "Team Collaborator", info: "Wondering if we can get JSON to naturally ramify in application...", repo_url: "https://github.com/dande313/team_collab", assistance_needed: true},
	{ title: "Tower of Hanoi", info: "Having difficulty getting disks to render correctly when displaying more than 40. Want to get up to 64.", repo_url: "https://github.com/dande313/Hanoi_v3", assistance_needed: true},
	{ title: "Trivia Game", info: "PLAY link troubleshooting", repo_url: "https://github.com/dande313/React_Trivia_Game", assistance_needed: true},
	{ title: "Tower of Hanoi", info: "AI attempting to escape the box.", repo_url: "https://github.com/dande313/Hanoi_v3", assistance_needed: false},
	{ title: "Science Journal", info: "Article show pages navigate using JQuery, but have difficulty when an article is deleted.", repo_url: "https://github.com/dande313/university-science-journal-V2", assistance_needed: true},
	{ title: "Top BoardGames Ruby CLI", info: "Working on adding prices for board games (located in dynamic JSON)", repo_url: "https://github.com/dande313/top_boardgames_ruby_cli", assistance_needed: false},
	{ title: "Art Collection", info: "Moving from Sinatra to Rails", repo_url: "https://github.com/dande313/Art-Collection", assistance_needed: true},
	{ title: "Team Collaborator", info: "Working in tidying up project with some sweet CSS", repo_url: "https://github.com/dande313/team_collab", assistance_needed: false},
	{ title: "Trivia Game", info: "Trouble getting answer box to automatically submit when timer runs out", repo_url: "https://github.com/dande313/React_Trivia_Game", assistance_needed: true},
	{ title: "Trivia Game", info: "Attempting to select 10 random trivia questions, when user hits PLAY", repo_url: "https://github.com/dande313/React_Trivia_Game", assistance_needed: true},
	{ title: "Tower of Hanoi", info: "Having difficulty getting disks to render correctly when displaying more than 40. Want to get up to 64.", repo_url: "https://github.com/dande313/Hanoi_v3", assistance_needed: true},
	{ title: "Trivia Game", info: "PLAY link troubleshooting", repo_url: "https://github.com/dande313/React_Trivia_Game", assistance_needed: true},
	{ title: "Tower of Hanoi", info: "AI attempting to escape the box.", repo_url: "https://github.com/dande313/Hanoi_v3", assistance_needed: false},
	{ title: "Art Collection", info: "Adjusting to allow for display of image thumbnail", repo_url: "https://github.com/dande313/Art-Collection", assistance_needed: false},
	{ title: "Science Journal", info: "Adding option to add Department.", repo_url: "https://github.com/dande313/university-science-journal-V2", assistance_needed: true},
	{ title: "Top BoardGames Ruby CLI", info: "Working on Alert when game is on sale", repo_url: "https://github.com/dande313/top_boardgames_ruby_cli", assistance_needed: true},
	{ title: "Trivia Game", info: "Adding JQuery render of questions", repo_url: "https://github.com/dande313/React_Trivia_Game", assistance_needed: false},
	{ title: "Tower of Hanoi", info: "Porting to Minecraft server", repo_url: "https://github.com/dande313/Hanoi_v3", assistance_needed: true},
	{ title: "Art Collection", info: "Adding copyright complaint submission form", repo_url: "https://github.com/dande313/Art-Collection", assistance_needed: false},
	{ title: "Art Collection", info: "Moving from Sinatra to Rails", repo_url: "https://github.com/dande313/Art-Collection", assistance_needed: true},
	{ title: "Team Collaborator", info: "Working in tidying up project with some sweet CSS", repo_url: "https://github.com/dande313/team_collab", assistance_needed: false},
	{ title: "Trivia Game", info: "Trouble getting answer box to automatically submit when timer runs out", repo_url: "https://github.com/dande313/React_Trivia_Game", assistance_needed: true},
	{ title: "Trivia Game", info: "Attempting to select 10 random trivia questions, when user hits PLAY", repo_url: "https://github.com/dande313/React_Trivia_Game", assistance_needed: true},
	{ title: "Tower of Hanoi", info: "Reworking instructions", repo_url: "https://github.com/dande313/Hanoi_v3", assistance_needed: false},
	{ title: "Art Collection", info: "Moving from Sinatra to Rails", repo_url: "https://github.com/dande313/Art-Collection", assistance_needed: true},
	{ title: "Art Collection", info: "Adding copyright complaint submission form", repo_url: "https://github.com/dande313/Art-Collection", assistance_needed: false},
	{ title: "Art Collection", info: "Moving from Sinatra to Rails", repo_url: "https://github.com/dande313/Art-Collection", assistance_needed: true},
	{ title: "Team Collaborator", info: "Working in tidying up project with some sweet CSS", repo_url: "https://github.com/dande313/team_collab", assistance_needed: false},
	{ title: "Trivia Game", info: "Trouble getting answer box to automatically submit when timer runs out", repo_url: "https://github.com/dande313/React_Trivia_Game", assistance_needed: true},
	{ title: "Trivia Game", info: "Attempting to select 10 random trivia questions, when user hits PLAY", repo_url: "https://github.com/dande313/React_Trivia_Game", assistance_needed: true},
	{ title: "Tower of Hanoi", info: "Reworking instructions", repo_url: "https://github.com/dande313/Hanoi_v3", assistance_needed: false},
	{ title: "Art Collection", info: "Moving from Sinatra to Rails", repo_url: "https://github.com/dande313/Art-Collection", assistance_needed: true},
	{ title: "Science Journal", info: "Adding links for creating topics.", repo_url: "https://github.com/dande313/university-science-journal-V2", assistance_needed: false},
	{ title: "Science Journal", info: "Need to transfer from SQLite3 gem to PG gem, required for Heroku deployment.", repo_url: "https://github.com/dande313/university-science-journal-V2", assistance_needed: true},
	{ title: "Top BoardGames Ruby CLI", info: "Fixed Redirect issue on create new", repo_url: "https://github.com/dande313/top_boardgames_ruby_cli", assistance_needed: false},
	{ title: "Team Collaborator", info: "Wondering if we can get JSON to naturally ramify in application...", repo_url: "https://github.com/dande313/team_collab", assistance_needed: true}
	])

